# Generated by Django 5.2.9 on 2025-12-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.RemoveField(
            model_name='event',
            name='videos',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='events/videos/'),
        ),
    ]
