# Generated by Django 5.2.9 on 2025-12-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_remove_event_images_remove_event_videos_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
