# Generated by Django 5.2.9 on 2025-12-15 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_remove_event_image_remove_event_video_eventimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='audio',
        ),
        migrations.CreateModel(
            name='SermonAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='sermons/audio/')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='contents.sermon')),
            ],
        ),
    ]
