# Generated by Django 5.2.9 on 2025-12-15 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_remove_sermon_audio_sermonaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='video',
        ),
        migrations.CreateModel(
            name='TestimonyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonies/images/')),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contents.testimony')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='testimonies/videos/')),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='contents.testimony')),
            ],
        ),
    ]
