# Generated by Django 5.2.9 on 2025-12-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminActionLog',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
